import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../../components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params }) {
  return (
    <html lang={params.locale}>
      <body className={inter.className}>
        <div className="flex flex-col min-h-screen w-full">
          <Header />
          <div className="flex flex-grow px-2 mt-6">{children}</div>
          <footer>Footer</footer>
        </div>
      </body>
    </html>
  );
}
